### user ###
- name: groupadd -g 48 apache
  group: name=apache gid=48 state=present
- name: useradd -g apache -u 48 apache
  user: name=apache group=apache uid=48 state=present

### yum ###
- name: yum -y install httpd httpd-devel mod_ssl
  yum: name={{ item }} state=present
  with_items:
    - httpd
    - httpd-devel
    - mod_ssl

### ssl ###
- when: ansible_distribution == 'Amazon'
  name: (Amazon) cd /etc/pki/tls/certs; cp /vagrant/ansible/roles/httpd/templates/etc/pki/tls/certs/localhost.crt ./; chmod 600 localhost.crt; chown root:root localhost.crt
  template: src="templates/etc/pki/tls/certs/localhost.crt" dest="/etc/pki/tls/certs/" mode=600 owner=root group=root force=no
- when: ansible_distribution == 'Amazon'
  name: (Amazon) cd /etc/pki/tls/private; cp /vagrant/ansible/roles/httpd/templates/etc/pki/tls/private/localhost.key ./; chmod 600 localhost.crt; chown root:root localhost.crt
  template: src="templates/etc/pki/tls/private/localhost.key" dest="/etc/pki/tls/private/" mode=600 owner=root group=root force=no

### conf ###
- name: cd /etc/httpd/conf; cp /vagrant/ansible/roles/httpd/templates/etc/httpd/conf/{.ht*,*} ./; chmod 644 {.ht*,*}; chown root:root {.ht*,*}
  template: src={{ item }} dest="/etc/httpd/conf/" mode=644 owner=root group=root backup=yes
  with_fileglob:
    - "templates/etc/httpd/conf/.ht*"
    - "templates/etc/httpd/conf/*"
  notify: systemctl restart httpd
- name: cd /etc/httpd/conf.d; cp /vagrant/ansible/roles/httpd/templates/etc/httpd/conf.d/{.ht*,*} ./; chmod 644 {.ht*,*}; chown root:root {.ht*,*}
  template: src={{ item }} dest="/etc/httpd/conf.d/" mode=644 owner=root group=root backup=yes
  with_fileglob:
    - "templates/etc/httpd/conf.d/.ht*"
    - "templates/etc/httpd/conf.d/*"
  notify: systemctl restart httpd
- name: cd /etc/httpd/conf.modules.d; cp /vagrant/ansible/roles/httpd/templates/etc/httpd/conf.modules.d/* ./; chmod 644 *; chown root:root *
  template: src={{ item }} dest="/etc/httpd/conf.modules.d/" mode=644 owner=root group=root backup=yes
  with_fileglob:
    - "templates/etc/httpd/conf.modules.d/*"
  notify: systemctl restart httpd

### log ###
- name: cd /var/log; mkdir -p httpd; chmod 750 httpd; chown apache:wheel httpd
  file: path="/var/log/httpd" state=directory mode=750 owner=apache group=wheel

- name: cd /etc/logrotate.d; cp /vagrant/ansible/roles/httpd/templates/etc/logrotate.d/httpd ./; chmod 644 httpd; chown root:root httpd
  template: src="templates/etc/logrotate.d/httpd" dest="/etc/logrotate.d/" mode=644 owner=root group=root backup=no

### html/cgi-bin ###
- name: cd /var/www; chmod 771 {.,html,cgi-bin}; chown apache:wheel {.,html,cgi-bin}
  file: path={{ item }} state=directory mode=771 owner=apache group=wheel
  with_items:
    - "/var/www"
    - "/var/www/html"
    - "/var/www/cgi-bin"

- name: cd /var/www/html; cp /vagrant/ansible/roles/httpd/templates/var/www/html/{.ht*,*} ./; chmod 664 {.ht*,*}; chown apache:wheel {.ht*,*}
  template: src={{ item }} dest="/var/www/html/" mode=664 owner=apache group=wheel backup=no
  with_fileglob:
    - "templates/var/www/html/.ht*"
    - "templates/var/www/html/*"
- name: cd /var/www/cgi-bin; cp /vagrant/ansible/roles/httpd/templates/var/www/cgi-bin/{.ht*,*} ./; chmod 664 {.ht*,*}; chown apache:wheel {.ht*,*}
  template: src={{ item }} dest="/var/www/cgi-bin/" mode=664 owner=apache group=wheel backup=no
  with_fileglob:
    - "templates/var/www/cgi-bin/.ht*"
    - "templates/var/www/cgi-bin/*"

### home ###
- name: mkdir -p /home/apache; chmod 700 /home/apache; chown apache:apache /home/apache
  file: path="/home/apache" state=directory mode=700 owner=apache group=apache
- name: ln -s /var/log/httpd /home/apache/log
  file: src="/var/log/httpd" dest="/home/apache/log" state=link
- name: ln -s /var/www/html /home/apache/html
  file: src="/var/www/html" dest="/home/apache/html" state=link
- name: ln -s /var/www/cgi-bin /home/apache/cgi-bin
  file: src="/var/www/cgi-bin" dest="/home/apache/cgi-bin" state=link

### backup ###
- name: mkdir -p /var/backup/httpd_contents; chmod 750 /var/backup/{.,httpd_contents}; chown root:wheel /var/backup/{.,httpd_contents}
  file: path={{ item }} state=directory mode=750 owner=root group=wheel
  with_items:
    - "/var/backup"
    - "/var/backup/httpd_contents"
- name: cd /etc/cron.daily; cp /vagrant/ansible/roles/httpd/templates/etc/cron.daily/backup_httpd_contents.cron ./; chmod 740 backup_httpd_contents.cron; chown root:wheel backup_httpd_contents.cron
  template: src="templates/etc/cron.daily/backup_httpd_contents.cron" dest="/etc/cron.daily/" mode=740 owner=root group=wheel backup=no
- name: cd /etc/logrotate.d; cp /vagrant/ansible/roles/httpd/templates/etc/logrotate.d/backup_httpd_contents ./; chmod 644 backup_httpd_contents; chown root:root backup_httpd_contents
  template: src="templates/etc/logrotate.d/backup_httpd_contents" dest="/etc/logrotate.d/" mode=644 owner=root group=root backup=no

### check/start ###
- name: apachectl configtest
  shell: apachectl configtest

- name: systemctl start httpd; systemctl enable httpd
  systemd: name=httpd state=started enabled=yes
