- name: yum -y install http://dev.mysql.com/get/mysql57-community-release-el7-11.noarch.rpm
  yum: name=http://dev.mysql.com/get/mysql57-community-release-el7-11.noarch.rpm state=present
- name: cd /etc/yum.repos.d; cp -a mysql-community.repo mysql-community.repo,def; sed -i -e "s/enabled\s*=\s*1/enabled=0/g" mysql-community.repo
  replace: dest=/etc/yum.repos.d/mysql-community.repo regexp="enabled\s*=\s*1" replace="enabled=0" backup=yes
