### yum ###
- import_tasks: repos.yml
- name: yum --enablerepo=mongodb-org install mongodb-org mongodb-org-server
  yum: name={{ item }} state=present enablerepo=mongodb-org
  with_items:
    - mongodb-org
    - mongodb-org-server

### conf ###
- name: cd /etc; cp /vagrant/ansible/roles/mongodb/templates/etc/mongod.conf ./; chmod 644 mongod.conf; chown root:root mongod.conf
  template: src="templates/etc/mongod.conf" dest="/etc/" mode=644 owner=root group=root backup=yes
  notify: systemctl restart mongod

### log ###
- name: cd /var/log; mkdir -p mongodb; chmod 750 mongodb; chown mongod:wheel mongodb
  file: path="/var/log/mongodb" state=directory mode=750 owner=mongod group=wheel
- name: cd /etc/logrotate.d; cp /vagrant/ansible/roles/mongodb/templates/etc/logrotate.d/mongodb ./; chmod 644 mongodb; chown root:root mongodb
  template: src="templates/etc/logrotate.d/mongodb" dest="/etc/logrotate.d/" mode=644 owner=root group=root backup=no

- name: cd /etc/cron.daily; cp /vagrant/ansible/roles/postgresql/templates/etc/cron.daily/logcompress_mongodb.cron ./; chmod 740 logcompress_mongodb.cron; chown root:wheel logcompress_mongodb.cron
  template: src="templates/etc/cron.daily/logcompress_mongodb.cron" dest="/etc/cron.daily/" mode=740 owner=root group=wheel backup=no
- name: cd /etc/logrotate.d; cp /vagrant/ansible/roles/postgresql/templates/etc/logrotate.d/logcompress_mongodb ./; chmod 644 logcompress_mongodb; chown root:root logcompress_mongodb
  template: src="templates/etc/logrotate.d/logcompress_mongodb" dest="/etc/logrotate.d/" mode=644 owner=root group=root backup=no

### start ###
- name: systemctl start mongod; systemctl enable mongod
  systemd: name=mongod state=started enabled=yes
