### user ###
- name: groupadd -g 490 nginx
  group: name=nginx gid=490 state=present
- name: useradd -g nginx -u 390 nginx
  user: name=nginx group=nginx uid=390 state=present

### yum ###
- import_tasks: roles/common/tasks/epel.yml
- name: yum -y --enablerepo=epel install nginx
  yum: name=nginx state=present enablerepo=epel
- name: yum -y install mod_ssl
  yum: name=mod_ssl state=present

### ssl ###
- when: ansible_distribution == 'Amazon'
  name: (Amazon) cd /etc/pki/tls/certs; cp /vagrant/ansible/roles/httpd/templates/etc/pki/tls/certs/localhost.crt ./; chmod 600 localhost.crt; chown root:root localhost.crt
  template: src="templates/etc/pki/tls/certs/localhost.crt" dest="/etc/pki/tls/certs/" mode=600 owner=root group=root force=no
- when: ansible_distribution == 'Amazon'
  name: (Amazon) cd /etc/pki/tls/private; cp /vagrant/ansible/roles/httpd/templates/etc/pki/tls/private/localhost.key ./; chmod 600 localhost.crt; chown root:root localhost.crt
  template: src="templates/etc/pki/tls/private/localhost.key" dest="/etc/pki/tls/private/" mode=600 owner=root group=root force=no

### conf ###
- name: cd /etc/nginx; cp /vagrant/ansible/roles/nginx/templates/etc/nginx/nginx.conf ./; chmod 644 nginx.conf; chown root:root nginx.conf
  template: src="templates/etc/nginx/nginx.conf" dest="/etc/nginx/" mode=644 owner=root group=root backup=yes
  notify: systemctl restart nginx
- name: cd /etc/nginx/conf.d; cp /vagrant/ansible/roles/nginx/templates/etc/nginx/conf.d/{.ht*,*} ./; chmod 644 {.ht*,*}; chown root:root {.ht*,*}
  template: src={{ item }} dest="/etc/nginx/conf.d/" mode=644 owner=root group=root backup=yes
  with_fileglob:
    - "templates/etc/nginx/conf.d/.ht*"
    - "templates/etc/nginx/conf.d/*"
  notify: systemctl restart nginx
- name: cd /etc/nginx/default.d; cp /vagrant/ansible/roles/nginx/templates/etc/nginx/default.d/{.ht*,*} ./; chmod 644 {.ht*,*}; chown root:root {.ht*,*}
  template: src={{ item }} dest="/etc/nginx/default.d/" mode=644 owner=root group=root backup=yes
  with_fileglob:
    - "templates/etc/nginx/default.d/.ht*"
    - "templates/etc/nginx/default.d/*"
  notify: systemctl restart nginx

### log ###
- name: cd /var/log; mkdir -p nginx; chmod 750 nginx; chown nginx:wheel nginx
  file: path="/var/log/nginx" state=directory mode=750 owner=nginx group=wheel

- name: cd /etc/logrotate.d; cp /vagrant/ansible/roles/nginx/templates/etc/logrotate.d/nginx ./; chmod 644 nginx; chown root:root nginx
  template: src="templates/etc/logrotate.d/nginx" dest="/etc/logrotate.d/" mode=644 owner=root group=root backup=no

### logwatch ###
- name: ln -s /usr/share/logwatch/scripts/services/http /usr/share/logwatch/scripts/services/nginx
  file: src="/usr/share/logwatch/scripts/services/http" dest="/usr/share/logwatch/scripts/services/nginx" state=link
- name: ln -s /usr/share/logwatch/scripts/services/http-error /usr/share/logwatch/scripts/services/nginx-error
  file: src="/usr/share/logwatch/scripts/services/http-error" dest="/usr/share/logwatch/scripts/services/nginx-error" state=link
- name: cd /usr/share/logwatch/default.conf/services; cp /vagrant/ansible/roles/nginx/templates/usr/share/logwatch/default.conf/services/nginx{,-error}.conf ./; chmod 644 nginx{,-error}.conf; chown root:root nginx{,-error}.conf
  template: src={{ item }} dest="/usr/share/logwatch/default.conf/services/" mode=644 owner=root group=root backup=yes
  with_fileglob:
    - "templates/usr/share/logwatch/default.conf/services/nginx.conf"
    - "templates/usr/share/logwatch/default.conf/services/nginx-error.conf"
- name: cd /usr/share/logwatch/default.conf/logfiles; cp /vagrant/ansible/roles/nginx/templates/usr/share/logwatch/default.conf/logfiles/nginx{,-error}.conf ./; chmod 644 nginx{,-error}.conf; chown root:root nginx{,-error}.conf
  template: src={{ item }} dest="/usr/share/logwatch/default.conf/logfiles/" mode=644 owner=root group=root backup=yes
  with_fileglob:
    - "templates/usr/share/logwatch/default.conf/logfiles/nginx.conf"
    - "templates/usr/share/logwatch/default.conf/logfiles/nginx-error.conf"

### html ###
- name: cd /usr/share/nginx; chmod 771 {.,html}; chown nginx:wheel {.,html}
  file: path={{ item }} state=directory mode=771 owner=nginx group=wheel
  with_items:
    - "/usr/share/nginx"
    - "/usr/share/nginx/html"

- name: cd /usr/share/nginx/html; rm {50x.html,nginx-logo.png,poweredby.png}
  file: path={{ item }} state=absent
  with_items:
    - "/usr/share/nginx/html/50x.html"
    - "/usr/share/nginx/html/nginx-logo.png"
    - "/usr/share/nginx/html/poweredby.png"
- name: cd /usr/share/nginx/html; cp /vagrant/ansible/roles/nginx/templates/usr/share/nginx/html/* ./; chmod 664 *; chown nginx:wheel *
  template: src={{ item }} dest="/usr/share/nginx/html/" mode=664 owner=nginx group=wheel backup=no
  with_fileglob:
    - "templates/usr/share/nginx/html/*"

- name: ln -s /usr/share/nginx/html /home/nginx/html
  file: src="/usr/share/nginx/html" dest="/home/nginx/html" state=link

### home ###
- name: ln -s /var/log/nginx /home/nginx/log
  file: src="/var/log/nginx" dest="/home/nginx/log" state=link
- name: ln -s /usr/share/nginx/html /home/nginx/html
  file: src="/usr/share/nginx/html" dest="/home/nginx/html" state=link

### WordPress ###
- when: hosts_env == 'development'
  name: (development) ln -s /vagrant/src/wordpress /usr/share/nginx/wordpress
  file: src="/vagrant/src/wordpress" dest="/usr/share/nginx/wordpress" state=link
- when: hosts_env != 'development'
  name: (!development) test ! -e /usr/share/nginx/wordpress
  stat: path=/usr/share/nginx/wordpress
  register: f
- when: hosts_env != 'development' and not f.stat.exists
  name: (!development & first) ln -s /usr/share/nginx/html /usr/share/nginx/wordpress
  file: src="/usr/share/nginx/html" dest="/usr/share/nginx/wordpress" state=link
- name: ln -s /usr/share/nginx/wordpress /home/nginx/wordpress
  file: src="/usr/share/nginx/wordpress" dest="/home/nginx/wordpress" state=link

### check/start ###
- name: nginx -t -c /etc/nginx/nginx.conf
  shell: nginx -t -c /etc/nginx/nginx.conf

- name: systemctl start nginx; systemctl enable nginx
  systemd: name=nginx state=started enabled=yes
