# Support [CentOS7]
- hosts: all
  max_fail_percentage: 0
  become: true
  roles:
    - role: common
      tags: common
    # Use chronyd(default ntp client)
    - role: chronyd
      tags: chronyd
    # Use Postfix(localhost only)
    - role: postfix
      tags: postfix
    # Use sshd
    - role: sshd
      tags: sshd

- hosts: db-servers
  max_fail_percentage: 0
  become: true
  roles:
    # Use MariaDB(MySQL derived)
    - role: mariadb
      tags: mariadb
    # Use MySQL 5.6
#    - role: mysql56
#      tags: mysql56
    # Use MySQL 5.7
#    - role: mysql57
#      tags: mysql57
    # Use PostgreSQL
    - role: postgresql
      tags: postgresql
    # Use PostgreSQL 9.6
#    - role: postgresql96
#      tags: postgresql96
    # Use Redis
    - role: redis
      tags: redis
    # Use MongoDB
    - role: mongodb
      tags: mongodb

- hosts: web-servers
  max_fail_percentage: 0
  become: true
  roles:
    # Use ImageMagick
    - role: imagick
      tags: imagick
    # Use Java 1.8
    - role: java18
      tags: java18
    # Use Tomcat
    - role: tomcat
      tags: tomcat
    # Use Let's Encrypt
    - role: letsencrypt
      tags: letsencrypt
    # Use Apache  *** Tips: Please change or add [DocumentRoot,Require ip] from [roles/httpd/templates/etc/httpd/conf.d/z_front.conf,allow-ip.inc]
    - role: httpd
      tags: httpd
    # Use PHP for Apache  *** Tips: It is better to delete unnecessary [ImageMagick,MariaDB/MySQL,PostgreSQL,Redis,MongoDB] from [roles/php-httpd/tasks/main.yml]
    - role: php-httpd
      tags: php-httpd
    # Use PHP 7.2 for Apache  *** Tips: It is better to delete unnecessary [ImageMagick,MariaDB/MySQL,PostgreSQL,Redis,MongoDB] from [roles/php72-httpd/tasks/main.yml]
#    - role: php72-httpd
#      tags: php72-httpd
    # Use PHP 7.3 for Apache  *** Tips: It is better to delete unnecessary [ImageMagick,MariaDB/MySQL,PostgreSQL,Redis,MongoDB] from [roles/php73-httpd/tasks/main.yml]
#    - role: php73-httpd
#      tags: php73-httpd
   # Use Nginx
#    - role: nginx
#      tags: nginx
    # Use PHP for Nginx  *** Tips: It is better to delete unnecessary [ImageMagick,MariaDB/MySQL,PostgreSQL,Redis,MongoDB] from [roles/php-nginx/tasks/main.yml]
#    - role: php-nginx
#      tags: php-nginx
    # Use PHP 7.2 for Nginx  *** Tips: It is better to delete unnecessary [ImageMagick,MariaDB/MySQL,PostgreSQL,Redis,MongoDB] from [roles/php72-nginx/tasks/main.yml]
#    - role: php72-nginx
#      tags: php72-nginx
    # Use PHP 7.3 for Nginx  *** Tips: It is better to delete unnecessary [ImageMagick,MariaDB/MySQL,PostgreSQL,Redis,MongoDB] from [roles/php73-nginx/tasks/main.yml]
    # TODO: (Amazon) Error php-pecl-redis, php-mongodb
#    - role: php73-nginx
#      tags: php73-nginx
    # Use Squid
    - role: squid
      tags: squid
