# Support [CentOS7]
- hosts: all
  max_fail_percentage: 0
  become: true
  roles:
    - role: common
      tags: common
    # Use chronyd(default ntp client)
    - role: chronyd
      tags: chronyd
    # Use Postfix(localhost only)
    - role: postfix
      tags: postfix
    # Use sshd
    - role: sshd
      tags: sshd

- hosts: db-servers
  max_fail_percentage: 0
  become: true
  roles:
    # Use MariaDB(MySQL derived)
    - role: mariadb
      tags: mariadb
    # Use PostgreSQL
    - role: postgresql
      tags: postgresql
    # Use Redis
    - role: redis
      tags: redis

- hosts: web-servers
  max_fail_percentage: 0
  become: true
  roles:
    # Use Apache  *** Tips: Please change or add [DocumentRoot,Require ip] from [roles/httpd/templates/etc/httpd/conf.d/z_front.conf,allow-ip.inc]
    - role: httpd
      tags: httpd
    # Use PHP for Apache  *** Tips: It is better to delete unnecessary [ImageMagick,MariaDB,PostgreSQL,Redis] from [roles/php-httpd/tasks/main.yml]
    - role: php-httpd
      tags: php-httpd
