# Support [CentOS7]
- hosts: all
  max_fail_percentage: 0
  become: true
  roles:
    - role: common
      tags: common
    # Use chronyd(default ntp client)
    - role: chronyd
      tags: chronyd
    # Use Postfix(localhost only)
    - role: postfix
      tags: postfix
    # Use sshd
    - role: sshd
      tags: sshd
